### ISSUE TITLE
gcr-cleaner doesn't work out of the box

### ISSUE THREAD

**Issue by alazakoa** [sethvargo/gcr-cleaner#29]
Job configuration:
```
gcloud scheduler jobs create http "gcrclean-batch-server" \
  --project ${PROJECT_ID} \
  --description "Cleanup ${REPO}" \
  --uri "${SERVICE_URL}/http" \
  --message-body "{\"repo\":\"${REPO}\", \"allow_tagged\":true, \"grace\":\"480h\"}" \
  --oidc-service-account-email "gcr-cleaner-invoker@${PROJECT_ID}.iam.gserviceaccount.com" \
  --schedule "0 0 * * *" \
  --time-zone="US/Eastern"
```

Google Cloud error message:
```
{
textPayload: "The request failed because either the HTTP response was malformed or connection to the instance had an error."
insertId: "id"
httpRequest: {
requestMethod: "POST"
requestUrl: "example.url"
requestSize: "1311"
status: 503
responseSize: "664"
userAgent: "Google-Cloud-Scheduler"
latency: "0.379463365s"
protocol: "HTTP/1.1"
}
resource: {
type: "cloud_run_revision"
labels: {5}
}
timestamp: "2021-04-06T20:31:53.024408Z"
severity: "ERROR"
labels: {1}
logName: "projects/example-internal/logs/run.googleapis.com%2Frequests"
trace: "projects/example-internal/traces/bdc53a52ab28121e4819fb006a9f6fe5"
receiveTimestamp: "2021-04-06T20:31:53.027902663Z"
}
```

```
http: panic serving 169.254.8.129:38751: runtime error: index out of range [0] with length 0
goroutine 13 [running]:
net/http.(*conn).serve.func1(0xc00019e0a0)
	net/http/server.go:1801 +0x147
panic(0x74c000, 0xc0003dd440)
	runtime/panic.go:975 +0x47a
github.com/sethvargo/gcr-cleaner/pkg/gcrcleaner.(*Cleaner).shouldDelete(0xc00000c200, 0x18c7a5d0, 0xc0002623c0, 0x34, 0x3019d7c0, 0xed7c0af6b, 0x98ec60, 0x3019d7c0, 0xed7c0b02f, 0x98ec60, ...)
	github.com/sethvargo/gcr-cleaner/pkg/gcrcleaner/cleaner.go:165 +0x1b8
github.com/sethvargo/gcr-cleaner/pkg/gcrcleaner.(*Cleaner).Clean(0xc00000c200, 0xc0001a4060, 0x2c, 0x326499c2, 0xed7e45e38, 0x0, 0x1, 0x0, 0xc00019e1e0, 0x0, ...)
	github.com/sethvargo/gcr-cleaner/pkg/gcrcleaner/cleaner.go:82 +0x82c
github.com/sethvargo/gcr-cleaner/pkg/gcrcleaner.(*Server).clean(0xc00000e058, 0x7d6a20, 0xc0000663c0, 0x7d4480, 0xc000184120, 0xc000014225, 0xc0001a4000, 0x0, 0x0)
	github.com/sethvargo/gcr-cleaner/pkg/gcrcleaner/server.go:142 +0x51a
github.com/sethvargo/gcr-cleaner/pkg/gcrcleaner.(*Server).HTTPHandler.func1(0x7d97e0, 0xc0001840e0, 0xc000058700)
	github.com/sethvargo/gcr-cleaner/pkg/gcrcleaner/server.go:94 +0x5b
net/http.HandlerFunc.ServeHTTP(0xc0000101a0, 0x7d97e0, 0xc0001840e0, 0xc000058700)
	net/http/server.go:2042 +0x44
net/http.(*ServeMux).ServeHTTP(0xc000066200, 0x7d97e0, 0xc0001840e0, 0xc000058700)
	net/http/server.go:2417 +0x1ad
net/http.serverHandler.ServeHTTP(0xc000184000, 0x7d97e0, 0xc0001840e0, 0xc000058700)
	net/http/server.go:2843 +0xa3
net/http.(*conn).serve(0xc00019e0a0, 0x7d9ea0, 0xc000066340)
	net/http/server.go:1925 +0x8ad
created by net/http.(*Server).Serve
	net/http/server.go:2969 +0x36c
```

Any idea what's going on here?

**Comment by sethvargo** [comment]
I think this is caused by https://github.com/sethvargo/gcr-cleaner/pull/28 which is fixed at HEAD

**Comment by alazakoa** [comment]
Has this image been updated? `"us-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner" `

**Comment by sethvargo** [comment]
No, not yet. I was going to wait until next week.

**Comment by sethvargo** [comment]
The latest version has been updated.
